os: linux
sudo: required
language: "minimal"
services:
  - docker

jobs:
  include:
    - name: "tests"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/tests.sh $DOCKER_IMAGE
    - name: "coverage"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/coverage.sh $DOCKER_IMAGE

notifications:
  email: false
